In [1]:
%matplotlib inline

In [2]:
from __future__ import print_function
import torch

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5311, 0.5193, 0.8208],
        [0.9339, 0.9561, 0.3391],
        [0.0673, 0.7717, 0.3168],
        [0.0789, 0.9816, 0.6596],
        [0.0168, 0.8726, 0.8720]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.8188,  0.8216,  1.6255],
        [ 1.1288,  1.7653, -0.0305],
        [ 0.1841, -1.0356, -0.4799],
        [ 1.6111, -0.1195, -0.9373],
        [ 0.1880,  0.0242, -0.1981]])


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.2567,  0.9658,  2.3606],
        [ 1.5206,  2.3687,  0.4283],
        [ 0.4449, -0.2476,  0.1601],
        [ 2.3635, -0.0723, -0.7433],
        [ 0.9726,  0.6323,  0.0834]])


Addition: syntax 2



In [10]:
print(torch.add(x, y))

tensor([[ 1.2567,  0.9658,  2.3606],
        [ 1.5206,  2.3687,  0.4283],
        [ 0.4449, -0.2476,  0.1601],
        [ 2.3635, -0.0723, -0.7433],
        [ 0.9726,  0.6323,  0.0834]])


Addition: providing an output tensor as argument



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.2567,  0.9658,  2.3606],
        [ 1.5206,  2.3687,  0.4283],
        [ 0.4449, -0.2476,  0.1601],
        [ 2.3635, -0.0723, -0.7433],
        [ 0.9726,  0.6323,  0.0834]])


Addition: in-place



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.2567,  0.9658,  2.3606],
        [ 1.5206,  2.3687,  0.4283],
        [ 0.4449, -0.2476,  0.1601],
        [ 2.3635, -0.0723, -0.7433],
        [ 0.9726,  0.6323,  0.0834]])


In [13]:
print(x[:, 1])

tensor([ 0.8216,  1.7653, -1.0356, -0.1195,  0.0242])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.0752])
-1.075222373008728


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor


In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [20]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([-0.0752], device='cuda:0')
tensor([-0.0752], dtype=torch.float64)
